---
layout: post
title: The 3/5 Compromise and Lessons for Institutional Reform
tags: Big+Picture
---

As you might have guessed, I like numbers. I like using them to understand the world, and when I see them being used in the world, I like to understand how they are being used. Often, this means understanding simple or complex mathematical systems, but sometimes it means understanding one number, and *why* it was chosen for a special purpose in the real world. Today's post came out of such a quest for me: to understand why America's founding fathers chose 3/5 for the 3/5 Compromise. This journey led me to considering some deeper truths about institutional reform, which has implications for anyone interested in the question of how we actually change our political systems into something better. 

Before I get any further with this, I need to say something about the language I use in this post. As you also may have guessed, I'll be exploring how the choice of 3/5 is, in some sense, optimal, as this is a recurring theme on this blog. However, I don't mean to imply that the overall system of slavery, including how it affected apportionment under the Constitution, was good in any sense. Slavery was an immoral system that the USA inherited from its colonial beginnings, which constituted the lifelong torture of millions of people, and directly lead to the bloodiest war for Americans in history. Although the Civil War ended slavery in America, it could not remove all of the stains it left on our country. In order to better understand and ultimately remove those stains that still remain, it helps to learn about their origin, and the 3/5 Compromise is an important part of that origin. So we're going to talk about it, while trying to keep in mind that underneath all the numbers in to today's discussion lies a history of immense human suffering.

The 3/5 Compromise was the resolution our founders devised to a problem they faced when drafting the Constitution, that of apportionment. Apportionment, today, refers to the process of determining how many of the 435 Representatives in the House are assigned to each of the 50 states, with the goal of assigning Representatives in proportion with the population of each state. There are other fundamental problems with apportionment that the new nation would need to solve ([this video](https://www.youtube.com/watch?v=GVhFBujPlVo) is an excellent and entertaining introduction; these problems also led to the first ever use of the presidential veto), but the founders needed to first decide how population counts should include slaves. Because a higher population would mean more Representatives, which would mean more power, states with lots of slaves (the South) wanted them to be counted, in full, while states with few slaves (the North) wanted them not to be counted at all. Each side offered moralistic arguments about whether it was more morally right to count slaves or not to count slaves, and James Madison offered his own moralistic argument for why a compromise was right, but the point is that the 3/5 Compromise, where each slave would be counted as 3/5 of a free person, was *the result of a negotiation over the balance of power*. The reason that a compromise was possible is that both sides benefited from a strong national constitution, so there was a range of options that the North and South would both prefer to keeping the Articles of Confederation. 

The only question that remains is: why 3/5? Why not 1/2, or 2/3, or 3/8? To answer this question well, we have to understand how the delegates at the Constitutional Convention settled on that number. And the answer is simple: that number had already been agreed upon as a compromise ratio at the Contentental Congress in 1783 (under the Articles of Confederation). However, under the Articles of Confederation, each state had equal power in Congress, so the compromise wasn't about that - it was about taxes. The exact history is a little hairy, but the bottom line is that Congress wanted to apportion *taxes* to the states based on population, and the same question of how to count slaves posed a problem. However, at that time the states with more slaves wanted them to be counted as less, for a lower tax burden, while the states with fewer wanted them to be counted as more. If it seems odd that the same number should be a good compromising value for these two, seemingly opposite negotiations, it may help to formalize these negotiations.

Let's first look at the 1783 negotiation, simpifying it to one between Northern and Southern states: 

<img src="/assets/jupyter/1783_negotiations.jpg" alt="1783 Negotiation" width="600" />

The x-axis shows the range of possible ratios that Congress might have agreed upon in a compromise, and the y-axis shows hypothetical payoffs that both sides might get from each possible outcome. By payoffs, I mean some abstract notion of how happy the negotiators and those they represent are as a result of the negotiation. As we covered, the North preferred a higher ratio in 1783 so that the South would shoulder more of the tax burden, and the South preferred a lower one. And as at the constitutional convention, there was some benefit to both sides that derived from the improvement to the Articles of Confederation, such that there is a range of ratios where both sides would benefit (positive payoff) from accepting that ratio. The point where both lines cross is where the balance of power does not change: both sides benefit equally. We do not know if 3/5 is exactly this point, but we can bet that the negotiators tried to find a point reasonably close to it. Passing the resolution required 9 out of 13 states to approve, so if more than 4 states thought they were getting the bad end of the deal, they would not vote for it and it would not pass.

Now consider how things might've been different in 1787:

<img src="/assets/jupyter/1787_negotiations.jpg" alt="1787 Negotiation" width="600" />

As we discussed, the preferences are now switched, with the North wanting a lower ratio and the South a higher ratio, but the important point is that the intersection of the curves does not move horizontally. This is because I am assuming that both sides benefited equally from a new constitution, the same as they benefited equally from improving the Articles of Confederation. Then the relationship between the 1783 plot and the 1787 plot is just a vertical distortion of both curves, which will not move the intersection horizontally. If 3/5 did not change the balance of power before, it still does not, and remains the compromise where neither side will think they're getting the bad end of the deal. Reading accounts of the convention, you also get the sense that there was a lot of work to do, and no one wanted to waste time rehashing a negotiation that had essentially happened four years earlier.

However, this is not a great answer to our original question: the delegates at the 1787 Convention used 3/5 because the delegates at the 1783 Congress had already chosen it? Hardly statisfying. 

So now let's ask why they chose it in 1783. To answer this, we have to get a little deeper into the hairy history of the Articles of Confederation, and even earlier. In 1775, the "United Colonies" had just entered into war with Britain, and needed to raise money for General Washington's army. There wasn't a lot of time to do anything too complicated, so the Congress decided to apportion taxes to the colonies in proportion with *total population* (slaves counted the same as free persons). The Articles of Confederation were approved by congress in 1777 and ratified by the states in 1781, a great step in legitimizing and organizing the national government. The articles stated that the federal government would request that states pay taxes in proportion to their *wealth*, not population, presumably because this is just a more fair system, as wealth is more closely related to ability to pay. However, estimating wealth is harder than estimating population, so Congress continued to request payments from the states in proportion to total population, but making massive adjustments to account for occupation by British troops, seemingly going through negotiations for every request over these adjustments. In 1783, the Revolutionary War was ending, and the delegates sought to extablish a formula that would not require negotiating every request for funds, would not require a difficult estimation process, and would accurately reflect ability to pay (if only because this is what the old system was, at least in theory, and so maintaining this would not change the balance of power). They settled on the 3/5 Compromise as the formula that best acheived this.

I have done a lot of digging around trying to get some estimate of how much wealth each state had around 1783 as a means of understanding how the 3/5 ratio best achieved this (I initially conceived of this post as a "technical deep-dive"). Unfortunately, the government never carried out an evaluation under the Articles of Confederation, and I could not find any scholarly estimates that reliably estimate the wealth of individual states. Additionally, since the government never actually imposed the wealth tax, we don't know for sure what kinds of wealth would've been taxed. The Articles of Confederation state that the taxes requested from each state shall be "in proportion to the value of all land within each state, granted to or surveyed for any Person, as such land and the buildings and improvements thereon shall be estimated." Maybe some schalars who know more about the time period could tell you how such a tax would probably factor in various kinds of wealth and slaves, but I think we'll probably never know for certain. Even if slaves would not directly be factored into wealth estimates, they might indirectly increase the value of other things owned by their masters. However, a very simple piece of data from the period gives us the right ballpark of 3/5: the ratio of the average price of a slave to the wealth of a freeperson (not including slaves they owned). Alice Hanson Jones, in her landmark work "Wealth of a nation to be: the American colonies on the eve of the Revolution," estimates the average price of a slave in 1774 (9 years before the 3/5 ratio was first agreed upon) at 34 pounds (page 114), and the "private physical nonhuman wealth" (not including non-physical wealth like debt and credit or human wealth, i.e. slaves and indentured servants) at 48.4 pounds (page 58). This measurement of wealth is probably as appropriate as any, since the Articles of Confederation definitely refer to physical wealth. Thus a reasonable formula for a freeperson's taxable wealth (assuming slaves would somehow be counted as wealth) is:

Wealth = 48.4 + 34 * (number of slaves owned).

Thus, in the total wealth of a state, every slave adds 34/48.4 = 0.7 of the taxable value of a freeperson, on average, which is close-ish to 3/5 = 0.6. The discrepancy is large enough that it doesn't tell us why 3/5 was chosen over 2/3, but there are so many unknowns here that we shouldn't be too disappointed by that.

The main point is that
1) the 3/5 ratio made relatively small changes to the balance of power in 1783, and this is why it was popular enough to pass in Congress. Even if some states were a little worse off, they benefited from having a federal government that could request taxes fairly without having to perform prohibitively costly and arbitrary surveys of the entire country. This is essentially the same as the hope I alluded to when [discussing the potential for electoral reform that eliminates gerrymandering](https://zdeblick.github.io/2025/03/26/Representation.html): the fact that neither party benefits much from gerrymandering on a national level means that a reform eliminating it is possible, politically. 

Stepping back to the timeline leading up to the Constitution, another lesson is evident: 
2) finding compromises takes work, so it's often more efficient to re-use existing compromises. This has the effect that some of the value of compromises is not just in what they achieve directly, but in the precedent they set for future negotiations. 

And stepping back to today, I think there are a couple of important lessons. 
3) Firstly, as the President has just deployed 700 marines to Los Angeles against the will of the state and local government, it feels like we are as close to a civil war as we have been in a long time, maybe since the Civil War. Hopefully we are not that close, but still, it feels like we can learn something from the first time. In many senses, the 3/5 Compromise was a horrible compromise: it fixed the value of one kind of human as a fraction of that of another kind and it did nothing to address how the divide between states with and without slaves would grow in the decades to come. And yet, it ultimately made our Constitution possible (as well as that original improvement to taxation in 1783). We must strive to find such compromises that promote unity and avoid violence, even if they come with great costs. The people must protest for what they want without destroying property and endangering lives, the government must protect its ability to function without instigating or escalating violence, and both sides should seek bipartisan solutions that as many as possible can get on board with. 

Going back to point 2, why not try again to pass a bipartisan immigration bill like the one that was negotiated in 2023-4, but failed to pass because of presidential election politics?

And lastly,
4) at this point in our history, we have been through many compromises over issues that are no longer present, and some of these have left us with baggage. Some of this baggage is social-economic, such as the lingering racial inequality in America. We should address this baggage by eliminating systemic racism from our institutions and confronting our history as a nation - I think celebrating Juneteenth is a great step in this direction. However, some of our baggage is legal, such as the electoral college (in the U.S., the president is elected based on who wins the majority of "electors", and, for the most part, whoever wins a state wins all their electors, a number proportional to the state's population count). If that seems unrelated, consider this: in a time when a slave-owner's vote is supposed to count for more, but slaves themselves are not allowed to vote, what simpler way is there to elect a president than with the electoral college? Note that I'm not arguing here that there are no other reasons to have the electoral college that are still relevant today, I'm just saying that there is one big reason it was initially created that has not been relevant for 160 years. As we try to improve our political systems, we should be on the lookout for institutions whose design is based on reasons that are no longer relevant. 

Broadly, taking on baggage from compromises and other acts is inevitable, but if we create too much baggage, or don't deal with it quickly enough, we will soon drown in it, just like with the national debt.



P.S.

A couple of notes that I wanted to add because I thought they were worth knowing, but the main post is too long already and they're less related to the main message:

1) Although the 3/5 Compromise was passed by congress in 1783, it was [never ratified by New Hampshire, Rhode Island, South Carolina, and Georgia](https://www.loc.gov/resource/llscdam.lljc030/?st=pdf&pdfPage=109), and ratification by all states was necessary to ammend the Articles. However, the ratio seemingly was used in 1785 and 1786 anyways to determine quotas for each state.

2) One thing I didn't mention is that in the original constitution, the population counts (using the 3/5 compromise) are used not only for apportioning representatives, but also for determining tax quotas for the states, just like under the 1783 ammendment. It is understood, however, that representation in Congress was seen as more important than the tax burden, and so slave-owning states still wanted a higher ratio.

3) After all of that work coming up with a reasonably fair system for apportioning taxes without needing to do land surveys, the very first tax apportioned to the states in 1798 under the new Constitution ordered ... yep, you guessed it: land surveys. As the Constitution mandated, states were apportioned their share of the tax burden based on population, but states were required to tax individuals based on the value of their land (including improvements) and slaves. I just wonder if our Founders appreciated the irony in this sequence of decisions.

4) For all the problems with land value taxes, there is a natural reason why the early USA tried so hard to make them work: they are theoretically a great way to tax. They are fair because they tax in proportion to ability to pay (unlike requiring every person to pay an equal share) without disincentivizing productivity. Income tax disincentivizes working, capital gains tax disincentivizes investment, sales tax disincentivizes commerce, and tariffs disincentivize trade, but a land value tax incentivizes using land efficiently. If you are interested in this idea, check out [Henry George](https://en.wikipedia.org/wiki/Henry_George), or [this video about his work](https://www.youtube.com/watch?v=6c5xjlmLfAw).

5) I did say this in the main section but it's important enough to say again. You SHOULD protest to make sure our leaders know we are holding them accountable, but you SHOULD NOT commit acts of violence or vandalism, as this completely undermines your legitimacy and legitimizes the use of force to disrupt protest. If you are at a protest and you see someone instigating violence or vandalism, tell other protesters, especially the organizers, or even the police, and try to get them to stop without putting yourself in danger. They might be in need of some guidance, or they might be someone who is being paid to destabilize America. I'll be going to a non-violent protest this weekend. You should too!



